<?php

namespace Database\Seeders;

use App\Models\Restaurant;
use Illuminate\Database\Seeder;

class RestaurantSeeder extends Seeder
{
    public function run(): void
    {
        $restaurants = [
            [
                'name' => 'Broth & Barrel',
                'description' => 'A warm, contemporary ramen bar known for slow-simmered broths, crisp karaage, and a focused late-evening menu.',
                'location' => 'Dublin',
                'cuisine' => 'Japanese',
                'price_range' => 'Mid-range',
                'rating' => 4.7,
                'opening_hours' => 'Mon-Sun, 12:00-22:30',
                'phone' => '+353 1 410 2201',
                'website' => 'https://brothandbarrel.ie',
                'image_url' => 'https://images.unsplash.com/photo-1617093727343-374698b1b08d?auto=format&fit=crop&w=1200&q=80',
                'menu_highlights' => 'Tonkotsu ramen, spicy miso broth, chicken karaage',
            ],
            [
                'name' => 'Shoyu Lane',
                'description' => 'An intimate ramen kitchen serving layered broths, hand-cut noodles, and a small plates menu built for sharing.',
                'location' => 'Belfast',
                'cuisine' => 'Japanese',
                'price_range' => 'Mid-range',
                'rating' => 4.5,
                'opening_hours' => 'Tue-Sun, 13:00-21:30',
                'phone' => '+44 28 9041 1880',
                'website' => 'https://shoyulane.co.uk',
                'image_url' => 'https://images.unsplash.com/photo-1555126634-323283e090fa?auto=format&fit=crop&w=1200&q=80',
                'menu_highlights' => 'Shoyu ramen, pork gyoza, chilli cucumbers',
            ],
            [
                'name' => 'Morning Folk',
                'description' => 'A bright brunch spot with seasonal specials, proper coffee, and a menu that balances comfort dishes with lighter plates.',
                'location' => 'Drogheda',
                'cuisine' => 'Cafe',
                'price_range' => 'Budget',
                'rating' => 4.6,
                'opening_hours' => 'Daily, 08:00-16:00',
                'phone' => '+353 41 981 2045',
                'website' => 'https://morningfolk.ie',
                'image_url' => 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1200&q=80',
                'menu_highlights' => 'French toast, shakshuka, flat white',
            ],
            [
                'name' => 'The Buttered Bench',
                'description' => 'A polished all-day brunch room with great pastries, elegant egg dishes, and a reliable weekend queue.',
                'location' => 'Galway',
                'cuisine' => 'Brunch',
                'price_range' => 'Mid-range',
                'rating' => 4.8,
                'opening_hours' => 'Wed-Sun, 09:00-15:30',
                'phone' => '+353 91 762 814',
                'website' => 'https://thebutteredbench.ie',
                'image_url' => 'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=1200&q=80',
                'menu_highlights' => 'Eggs benedict, brown butter pancakes, seasonal granola',
            ],
            [
                'name' => 'Spice Circuit',
                'description' => 'A lively kitchen focused on fiery curries, layered sauces, and spice-forward plates that still feel balanced and precise.',
                'location' => 'Cork',
                'cuisine' => 'Indian',
                'price_range' => 'Mid-range',
                'rating' => 4.6,
                'opening_hours' => 'Daily, 12:30-22:00',
                'phone' => '+353 21 450 9982',
                'website' => 'https://spicecircuit.ie',
                'image_url' => 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?auto=format&fit=crop&w=1200&q=80',
                'menu_highlights' => 'Lamb madras, chilli garlic naan, tandoori cauliflower',
            ],
            [
                'name' => 'Fireleaf Kitchen',
                'description' => 'A modern Indian-inspired restaurant known for bold heat, smoky grills, and generous vegetarian options.',
                'location' => 'Dublin',
                'cuisine' => 'Indian',
                'price_range' => 'Mid-range',
                'rating' => 4.4,
                'opening_hours' => 'Mon-Sun, 12:00-22:00',
                'phone' => '+353 1 498 7782',
                'website' => 'https://fireleafkitchen.ie',
                'image_url' => 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=1200&q=80',
                'menu_highlights' => 'Chicken vindaloo, paneer tikka, masala fries',
            ],
            [
                'name' => 'Sugar Loom',
                'description' => 'An elegant dessert studio producing plated sweets, glossy pastries, and excellent coffee for slower afternoons.',
                'location' => 'Belfast',
                'cuisine' => 'Dessert',
                'price_range' => 'Mid-range',
                'rating' => 4.8,
                'opening_hours' => 'Tue-Sun, 11:00-20:00',
                'phone' => '+44 28 9032 7740',
                'website' => 'https://sugarloom.co.uk',
                'image_url' => 'https://images.unsplash.com/photo-1551024601-bec78aea704b?auto=format&fit=crop&w=1200&q=80',
                'menu_highlights' => 'Basque cheesecake, pistachio tart, hot chocolate',
            ],
            [
                'name' => 'Whisk & Berry',
                'description' => 'A crowd-pleasing dessert cafe built around layered cakes, fresh pastries, and bright fruit-led bakes.',
                'location' => 'Dundalk',
                'cuisine' => 'Dessert',
                'price_range' => 'Budget',
                'rating' => 4.5,
                'opening_hours' => 'Daily, 10:00-18:30',
                'phone' => '+353 42 933 8814',
                'website' => 'https://whiskandberry.ie',
                'image_url' => 'https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=1200&q=80',
                'menu_highlights' => 'Berry pavlova slice, lemon tart, cinnamon buns',
            ],
            [
                'name' => 'Quiet Roast',
                'description' => 'A calm coffee bar with soft interiors, dependable wifi, and a menu designed for long catchups or focused study sessions.',
                'location' => 'Drogheda',
                'cuisine' => 'Cafe',
                'price_range' => 'Budget',
                'rating' => 4.6,
                'opening_hours' => 'Mon-Sat, 08:00-18:00',
                'phone' => '+353 41 984 6018',
                'website' => 'https://quietroast.ie',
                'image_url' => 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=1200&q=80',
                'menu_highlights' => 'Pour-over coffee, almond croissant, toasties',
            ],
            [
                'name' => 'Lantern Coffee House',
                'description' => 'A design-led cafe with speciality coffee, relaxed seating, and a strong pastry case throughout the day.',
                'location' => 'Dublin',
                'cuisine' => 'Cafe',
                'price_range' => 'Budget',
                'rating' => 4.7,
                'opening_hours' => 'Daily, 07:30-18:30',
                'phone' => '+353 1 531 7801',
                'website' => 'https://lanterncoffeehouse.ie',
                'image_url' => 'https://images.unsplash.com/photo-1445116572660-236099ec97a0?auto=format&fit=crop&w=1200&q=80',
                'menu_highlights' => 'Batch brew, cardamom bun, whipped ricotta toast',
            ],
            [
                'name' => 'Riverside Sushi Club',
                'description' => 'A polished sushi restaurant with fresh nigiri, generous chirashi bowls, and excellent lunch value.',
                'location' => 'Galway',
                'cuisine' => 'Japanese',
                'price_range' => 'Mid-range',
                'rating' => 4.7,
                'opening_hours' => 'Tue-Sun, 12:00-22:00',
                'phone' => '+353 91 552 340',
                'website' => 'https://riversidesushiclub.ie',
                'image_url' => 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&w=1200&q=80',
                'menu_highlights' => 'Salmon nigiri, dragon roll, prawn tempura',
            ],
            [
                'name' => 'Sakura Table',
                'description' => 'A stylish sushi and small plates restaurant with a calm atmosphere and a strong omakase-inspired specials board.',
                'location' => 'Cork',
                'cuisine' => 'Japanese',
                'price_range' => 'Premium',
                'rating' => 4.8,
                'opening_hours' => 'Wed-Mon, 17:00-22:30',
                'phone' => '+353 21 434 7721',
                'website' => 'https://sakuratable.ie',
                'image_url' => 'https://images.unsplash.com/photo-1553621042-f6e147245754?auto=format&fit=crop&w=1200&q=80',
                'menu_highlights' => 'Chef selection sashimi, tuna maki, miso aubergine',
            ],
            [
                'name' => 'Patty District',
                'description' => 'A busy burger house serving smashed patties, loaded fries, and late-night trays that stay consistent.',
                'location' => 'Dublin',
                'cuisine' => 'Burgers',
                'price_range' => 'Budget',
                'rating' => 4.5,
                'opening_hours' => 'Daily, 12:00-23:30',
                'phone' => '+353 1 478 2104',
                'website' => 'https://pattydistrict.ie',
                'image_url' => 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=1200&q=80',
                'menu_highlights' => 'Double smash burger, bacon jam fries, vanilla shake',
            ],
            [
                'name' => 'Char House Social',
                'description' => 'A more refined burger and grill spot with house sauces, brisket specials, and a polished casual dining room.',
                'location' => 'Belfast',
                'cuisine' => 'Burgers',
                'price_range' => 'Mid-range',
                'rating' => 4.6,
                'opening_hours' => 'Tue-Sun, 12:00-22:30',
                'phone' => '+44 28 9077 6612',
                'website' => 'https://charhousesocial.co.uk',
                'image_url' => 'https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=1200&q=80',
                'menu_highlights' => 'Dry-aged cheeseburger, chilli cheese fries, grilled chicken burger',
            ],
            [
                'name' => 'Crust Society',
                'description' => 'A popular neighbourhood pizzeria with long-fermented dough, bright toppings, and a lively evening crowd.',
                'location' => 'Cork',
                'cuisine' => 'Italian',
                'price_range' => 'Mid-range',
                'rating' => 4.7,
                'opening_hours' => 'Daily, 12:00-22:30',
                'phone' => '+353 21 431 1026',
                'website' => 'https://crustsociety.ie',
                'image_url' => 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=1200&q=80',
                'menu_highlights' => 'Margherita, nduja pizza, burrata starter',
            ],
            [
                'name' => 'Stonedough',
                'description' => 'A relaxed pizza room with charred crusts, creative toppings, and reliably good takeaway slices.',
                'location' => 'Galway',
                'cuisine' => 'Italian',
                'price_range' => 'Budget',
                'rating' => 4.4,
                'opening_hours' => 'Tue-Sun, 13:00-22:00',
                'phone' => '+353 91 400 116',
                'website' => 'https://stonedough.ie',
                'image_url' => 'https://images.unsplash.com/photo-1541745537411-b8046dc6d66c?auto=format&fit=crop&w=1200&q=80',
                'menu_highlights' => 'Pepperoni hot honey, mushroom truffle pizza, garlic knots',
            ],
            [
                'name' => 'Olive & Ember',
                'description' => 'A romantic dining room built around candlelit service, seasonal plates, and a calm, premium atmosphere.',
                'location' => 'Dublin',
                'cuisine' => 'Modern European',
                'price_range' => 'Premium',
                'rating' => 4.8,
                'opening_hours' => 'Tue-Sun, 17:30-22:30',
                'phone' => '+353 1 611 2302',
                'website' => 'https://oliveandember.ie',
                'image_url' => 'https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&w=1200&q=80',
                'menu_highlights' => 'Short rib, wild mushroom pappardelle, chocolate fondant',
            ],
            [
                'name' => 'Harbour Table',
                'description' => 'A softly lit bistro serving share plates, seafood mains, and polished desserts that suit slower evenings.',
                'location' => 'Howth',
                'cuisine' => 'Seafood',
                'price_range' => 'Premium',
                'rating' => 4.7,
                'opening_hours' => 'Wed-Sun, 17:00-22:00',
                'phone' => '+353 1 839 4427',
                'website' => 'https://harbourtable.ie',
                'image_url' => 'https://images.unsplash.com/photo-1559339352-11d035aa65de?auto=format&fit=crop&w=1200&q=80',
                'menu_highlights' => 'Pan-fried hake, oysters, brown butter tart',
            ],
            [
                'name' => 'Green Hearth',
                'description' => 'A plant-forward restaurant proving vegan cooking can be deeply satisfying, colourful, and generous.',
                'location' => 'Galway',
                'cuisine' => 'Vegan',
                'price_range' => 'Mid-range',
                'rating' => 4.7,
                'opening_hours' => 'Tue-Sun, 12:00-21:30',
                'phone' => '+353 91 561 942',
                'website' => 'https://greenhearth.ie',
                'image_url' => 'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1200&q=80',
                'menu_highlights' => 'Miso aubergine bowl, crispy tofu bao, cashew cheesecake',
            ],
            [
                'name' => 'Root & Bloom',
                'description' => 'A bright vegan cafe with nourishing bowls, excellent juices, and one of the stronger weekday lunch offers in town.',
                'location' => 'Belfast',
                'cuisine' => 'Vegan',
                'price_range' => 'Budget',
                'rating' => 4.5,
                'opening_hours' => 'Mon-Sat, 09:00-17:30',
                'phone' => '+44 28 9044 8215',
                'website' => 'https://rootandbloom.co.uk',
                'image_url' => 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=1200&q=80',
                'menu_highlights' => 'Falafel bowl, green smoothie, almond brownie',
            ],
            [
                'name' => 'Market Noodle Bar',
                'description' => 'A casual Asian noodle spot with stir-fried specials, quick lunches, and strong vegetarian options.',
                'location' => 'Dundalk',
                'cuisine' => 'Asian',
                'price_range' => 'Budget',
                'rating' => 4.3,
                'opening_hours' => 'Mon-Sat, 12:00-21:00',
                'phone' => '+353 42 938 4421',
                'website' => 'https://marketnoodlebar.ie',
                'image_url' => 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=1200&q=80',
                'menu_highlights' => 'Dan dan noodles, chicken katsu curry, veg spring rolls',
            ],
            [
                'name' => 'Dockyard Tacos',
                'description' => 'A fun, loud taco room with grilled meats, spicy salsas, and a menu that works well for groups.',
                'location' => 'Belfast',
                'cuisine' => 'Mexican',
                'price_range' => 'Budget',
                'rating' => 4.4,
                'opening_hours' => 'Tue-Sun, 12:00-22:00',
                'phone' => '+44 28 9088 7719',
                'website' => 'https://dockyardtacos.co.uk',
                'image_url' => 'https://images.unsplash.com/photo-1513456852971-30c0b8199d4d?auto=format&fit=crop&w=1200&q=80',
                'menu_highlights' => 'Birria tacos, elote, habanero salsa',
            ],
            [
                'name' => 'Midnight Munch',
                'description' => 'A late-night comfort food counter serving loaded fries, wraps, wings, and fast post-night-out meals.',
                'location' => 'Dublin',
                'cuisine' => 'Late Night',
                'price_range' => 'Budget',
                'rating' => 4.2,
                'opening_hours' => 'Thu-Sun, 18:00-02:30',
                'phone' => '+353 1 590 4019',
                'website' => 'https://midnightmunch.ie',
                'image_url' => 'https://images.unsplash.com/photo-1525755662778-989d0524087e?auto=format&fit=crop&w=1200&q=80',
                'menu_highlights' => 'Loaded chicken fries, buffalo wings, doner wrap',
            ],
            [
                'name' => 'Harissa Lane',
                'description' => 'A modern Middle Eastern kitchen bringing smoky spice, generous mezze, and bold grilled dishes to the city centre.',
                'location' => 'Dublin',
                'cuisine' => 'Middle Eastern',
                'price_range' => 'Mid-range',
                'rating' => 4.7,
                'opening_hours' => 'Daily, 12:00-22:00',
                'phone' => '+353 1 514 1172',
                'website' => 'https://harissalane.ie',
                'image_url' => 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1200&q=80',
                'menu_highlights' => 'Lamb kofta, muhammara, spiced cauliflower',
            ],
            [
                'name' => 'Sea Salt Kitchen',
                'description' => 'A coastal-inspired seafood restaurant with bright flavours, sustainable sourcing, and generous fish-focused plates.',
                'location' => 'Galway',
                'cuisine' => 'Seafood',
                'price_range' => 'Premium',
                'rating' => 4.8,
                'opening_hours' => 'Wed-Sun, 17:00-22:00',
                'phone' => '+353 91 530 811',
                'website' => 'https://seasaltkitchen.ie',
                'image_url' => 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=1200&q=80',
                'menu_highlights' => 'Seafood linguine, grilled prawns, chowder',
            ],
            [
                'name' => 'Oak Room Bistro',
                'description' => 'A date-night favourite with refined mains, a composed wine list, and warm service that never feels stiff.',
                'location' => 'Cork',
                'cuisine' => 'Modern European',
                'price_range' => 'Premium',
                'rating' => 4.6,
                'opening_hours' => 'Tue-Sun, 17:30-22:00',
                'phone' => '+353 21 489 0225',
                'website' => 'https://oakroombistro.ie',
                'image_url' => 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1200&q=80',
                'menu_highlights' => 'Duck breast, truffle potatoes, crème brûlée',
            ],
        ];

        foreach ($restaurants as $restaurant) {
            Restaurant::updateOrCreate(
                ['name' => $restaurant['name']],
                $restaurant
            );
        }
    }
}
