<?php

namespace Database\Seeders;

use App\Models\Restaurant;
use Illuminate\Database\Seeder;

class RestaurantSeeder extends Seeder
{
    public function run(): void
    {
        $restaurants = [
            [
                'name' => 'Harbour Grill Social',
                'description' => 'A lively waterfront grill serving polished comfort food, stacked burgers, and generous sharing plates.',
                'location' => 'Dublin',
                'cuisine' => 'Modern Grill',
                'price_range' => 'Mid-range',
                'rating' => 4.5,
                'opening_hours' => '12:00 - 22:30',
                'phone' => '01 431 2201',
                'website' => 'https://harbourgrillsocial.example.com',
                'menu_highlights' => 'Dry-Aged Cheeseburger, Charred Corn Ribs, Truffle Chips',
            ],
            [
                'name' => 'The Gourmet Kitchen',
                'description' => 'A refined dining experience with high-quality ingredients and elegant presentation.',
                'location' => 'Cork',
                'cuisine' => 'Fine Dining',
                'price_range' => 'Luxury',
                'rating' => 4.8,
                'opening_hours' => '17:00 - 22:30',
                'phone' => '021 234 5678',
                'website' => 'https://gourmetkitchen.example.com',
                'menu_highlights' => 'Tasting Menu, Wagyu Steak, Wine Pairing',
            ],
            [
                'name' => 'Sushi World',
                'description' => 'Authentic Japanese cuisine with fresh sushi and sashimi.',
                'location' => 'Dublin',
                'cuisine' => 'Japanese',
                'price_range' => 'Expensive',
                'rating' => 4.6,
                'opening_hours' => '12:00 - 22:00',
                'phone' => '01 234 9876',
                'website' => 'https://sushiworld.example.com',
                'menu_highlights' => 'Salmon Nigiri, Dragon Roll, Miso Soup',
            ],
            [
                'name' => 'Pasta Palace',
                'description' => 'Fresh Italian pasta dishes with rich, traditional sauces.',
                'location' => 'Galway',
                'cuisine' => 'Italian',
                'price_range' => 'Mid-range',
                'rating' => 4.4,
                'opening_hours' => '12:00 - 21:30',
                'phone' => '091 222 3333',
                'website' => 'https://pastapalace.example.com',
                'menu_highlights' => 'Carbonara, Bolognese, Lasagna',
            ],
            [
                'name' => 'Burger Haven',
                'description' => 'Classic American burgers with generous portions and sides.',
                'location' => 'Limerick',
                'cuisine' => 'American',
                'price_range' => 'Mid-range',
                'rating' => 4.3,
                'opening_hours' => '11:00 - 22:00',
                'phone' => '061 555 1234',
                'website' => 'https://burgerhaven.example.com',
                'menu_highlights' => 'Cheeseburger, Loaded Fries, Milkshakes',
            ],
            [
                'name' => 'Taco Town',
                'description' => 'Bold Mexican flavours with fresh tacos and burritos.',
                'location' => 'Dublin',
                'cuisine' => 'Mexican',
                'price_range' => 'Mid-range',
                'rating' => 4.5,
                'opening_hours' => '12:00 - 23:00',
                'phone' => '01 998 7766',
                'website' => 'https://tacotown.example.com',
                'menu_highlights' => 'Beef Tacos, Burritos, Nachos',
            ],
            [
                'name' => 'Vegan Delight',
                'description' => 'Creative plant-based dishes made with fresh ingredients.',
                'location' => 'Cork',
                'cuisine' => 'Vegan',
                'price_range' => 'Mid-range',
                'rating' => 4.7,
                'opening_hours' => '10:00 - 20:00',
                'phone' => '021 987 6543',
                'website' => 'https://vegandelight.example.com',
                'menu_highlights' => 'Vegan Burger, Buddha Bowl, Smoothies',
            ],
            [
                'name' => 'Cafe Mocha',
                'description' => 'Cosy café known for coffee, pastries and brunch options.',
                'location' => 'Galway',
                'cuisine' => 'Cafe',
                'price_range' => 'Budget',
                'rating' => 4.2,
                'opening_hours' => '08:00 - 18:00',
                'phone' => '091 444 5555',
                'website' => 'https://cafemocha.example.com',
                'menu_highlights' => 'Cappuccino, Croissants, Pancakes',
            ],
            [
                'name' => 'Seafood Shack',
                'description' => 'Fresh coastal seafood dishes with generous portions.',
                'location' => 'Waterford',
                'cuisine' => 'Seafood',
                'price_range' => 'Expensive',
                'rating' => 4.6,
                'opening_hours' => '12:00 - 22:00',
                'phone' => '051 777 8888',
                'website' => 'https://seafoodshack.example.com',
                'menu_highlights' => 'Grilled Salmon, Fish & Chips, Prawns',
            ],
            [
                'name' => 'Pizza Planet',
                'description' => 'Wide variety of freshly made pizzas with quality toppings.',
                'location' => 'Dublin',
                'cuisine' => 'Italian',
                'price_range' => 'Mid-range',
                'rating' => 4.4,
                'opening_hours' => '12:00 - 23:00',
                'phone' => '01 777 9999',
                'website' => 'https://pizzaplanet.example.com',
                'menu_highlights' => 'Pepperoni Pizza, Margherita, BBQ Chicken',
            ],
            [
                'name' => 'Late Night Bites',
                'description' => 'Street-food style meals perfect for late-night cravings.',
                'location' => 'Dublin',
                'cuisine' => 'Street Food',
                'price_range' => 'Budget',
                'rating' => 4.0,
                'opening_hours' => '18:00 - 03:00',
                'phone' => '01 666 8888',
                'website' => 'https://latenightbites.example.com',
                'menu_highlights' => 'Wraps, Fries, Burgers',
            ],
            [
                'name' => 'Dragon House',
                'description' => 'Traditional Chinese dishes with bold flavours and authentic recipes.',
                'location' => 'Dublin',
                'cuisine' => 'Chinese',
                'price_range' => 'Mid-range',
                'rating' => 4.5,
                'opening_hours' => '12:00 - 22:30',
                'phone' => '01 555 1111',
                'website' => 'https://dragonhouse.example.com',
                'menu_highlights' => 'Sweet & Sour Chicken, Kung Pao Chicken, Dim Sum',
                ],
                [
                'name' => 'Spice Route',
                'description' => 'Rich and aromatic Indian cuisine with traditional spices and curries.',
                'location' => 'Cork',
                'cuisine' => 'Indian',
                'price_range' => 'Mid-range',
                'rating' => 4.7,
                'opening_hours' => '12:00 - 23:00',
                'phone' => '021 555 2222',
                'website' => 'https://spiceroute.example.com',
                'menu_highlights' => 'Butter Chicken, Biryani, Garlic Naan',
                ],
                [
                'name' => 'Bangkok Basil',
                'description' => 'Fresh and spicy Thai street food with vibrant flavours.',
                'location' => 'Galway',
                'cuisine' => 'Thai',
                'price_range' => 'Mid-range',
                'rating' => 4.6,
                'opening_hours' => '12:00 - 22:00',
                'phone' => '091 555 3333',
                'website' => 'https://bangkokbasil.example.com',
                'menu_highlights' => 'Pad Thai, Green Curry, Tom Yum Soup',
                ],
                [
                'name' => 'Seoul Kitchen',
                'description' => 'Authentic Korean BBQ and traditional dishes served fresh.',
                'location' => 'Dublin',
                'cuisine' => 'Korean',
                'price_range' => 'Expensive',
                'rating' => 4.8,
                'opening_hours' => '13:00 - 23:00',
                'phone' => '01 555 4444',
                'website' => 'https://seoulkitchen.example.com',
                'menu_highlights' => 'Korean BBQ, Bibimbap, Kimchi Stew',
                ],
                [
                'name' => 'Parisian Bistro',
                'description' => 'Elegant French dining with classic dishes and fine wines.',
                'location' => 'Cork',
                'cuisine' => 'French',
                'price_range' => 'Luxury',
                'rating' => 4.9,
                'opening_hours' => '17:00 - 23:00',
                'phone' => '021 555 6666',
                'website' => 'https://parisianbistro.example.com',
                'menu_highlights' => 'Coq au Vin, Escargot, Crème Brûlée',
                ],
                [
                'name' => 'Athens Taverna',
                'description' => 'Traditional Greek dishes with fresh ingredients and Mediterranean flair.',
                'location' => 'Galway',
                'cuisine' => 'Greek',
                'price_range' => 'Mid-range',
                'rating' => 4.5,
                'opening_hours' => '12:00 - 22:00',
                'phone' => '091 555 7777',
                'website' => 'https://athenstaverna.example.com',
                'menu_highlights' => 'Gyros, Moussaka, Souvlaki',
                ],
                [
                'name' => 'Istanbul Grill',
                'description' => 'Flame-grilled Turkish kebabs and rich Mediterranean dishes.',
                'location' => 'Dublin',
                'cuisine' => 'Turkish',
                'price_range' => 'Mid-range',
                'rating' => 4.4,
                'opening_hours' => '12:00 - 23:00',
                'phone' => '01 555 8888',
                'website' => 'https://istanbulgrill.example.com',
                'menu_highlights' => 'Doner Kebab, Lamb Shish, Baklava',
                ],
                [
                'name' => 'Beirut Mezze',
                'description' => 'Authentic Lebanese mezze platters and grilled specialties.',
                'location' => 'Cork',
                'cuisine' => 'Lebanese',
                'price_range' => 'Mid-range',
                'rating' => 4.6,
                'opening_hours' => '12:00 - 22:00',
                'phone' => '021 555 9999',
                'website' => 'https://beirutmezze.example.com',
                'menu_highlights' => 'Hummus, Shawarma, Falafel',
                ],
                [
                'name' => 'Barcelona Tapas',
                'description' => 'Spanish tapas bar offering small plates full of flavour.',
                'location' => 'Galway',
                'cuisine' => 'Spanish',
                'price_range' => 'Mid-range',
                'rating' => 4.5,
                'opening_hours' => '15:00 - 23:00',
                'phone' => '091 555 1212',
                'website' => 'https://barcelonatapas.example.com',
                'menu_highlights' => 'Patatas Bravas, Paella, Chorizo',
                ],
                [
                'name' => 'Addis Ababa Flavours',
                'description' => 'Authentic Ethiopian cuisine served with traditional injera bread.',
                'location' => 'Dublin',
                'cuisine' => 'Ethiopian',
                'price_range' => 'Mid-range',
                'rating' => 4.7,
                'opening_hours' => '12:00 - 22:00',
                'phone' => '01 555 3434',
                'website' => 'https://addisflavours.example.com',
                'menu_highlights' => 'Doro Wat, Injera, Lentil Stew',
                ],
                [
                'name' => 'Havana Street',
                'description' => 'Vibrant Caribbean-inspired street food with bold tropical flavours.',
                'location' => 'Waterford',
                'cuisine' => 'Caribbean',
                'price_range' => 'Mid-range',
                'rating' => 4.4,
                'opening_hours' => '12:00 - 22:30',
                'phone' => '051 555 5656',
                'website' => 'https://havanastreet.example.com',
                'menu_highlights' => 'Jerk Chicken, Plantains, Rice & Peas',
                ],
        ];

        foreach ($restaurants as $index => $restaurant) {
            $restaurant['image_url'] = $this->buildImageUrl(
                $restaurant['name'],
                $restaurant['cuisine'],
                $index + 1
            );

            Restaurant::updateOrCreate(
                ['name' => $restaurant['name']],
                $restaurant
            );
        }
    }

    private function buildImageUrl(string $name, string $cuisine, int $lock): string
    {
        $imageMap = [
            'Harbour Grill Social' => 'images/restaurants/american.jpg',
            'The Gourmet Kitchen' => 'images/restaurants/fine-dining.jpg',
            'Sushi World' => 'images/restaurants/japanese.jpg',
            'Pasta Palace' => 'images/restaurants/italian-bistro.jpg',
            'Burger Haven' => 'images/restaurants/fast-food.jpg',
            'Taco Town' => 'images/restaurants/mexican.jpg',
            'Vegan Delight' => 'images/restaurants/vegan.jpg',
            'Cafe Mocha' => 'images/restaurants/cafe.jpg',
            'Seafood Shack' => 'images/restaurants/seafood.jpg',
            'Pizza Planet' => 'images/restaurants/italian.jpg',
            'Late Night Bites' => 'images/restaurants/street-food.jpg',
            'Dragon House' => 'images/restaurants/chinese.jpg',
            'Spice Route' => 'images/restaurants/indian.jpg',
            'Bangkok Basil' => 'images/restaurants/thai.jpg',
            'Seoul Kitchen' => 'images/restaurants/korean.jpg',
            'Parisian Bistro' => 'images/restaurants/french.jpg',
            'Athens Taverna' => 'images/restaurants/greek.jpg',
            'Istanbul Grill' => 'images/restaurants/turkish.jpg',
            'Beirut Mezze' => 'images/restaurants/lebanese.jpg',
            'Barcelona Tapas' => 'images/restaurants/spanish.jpg',
            'Addis Ababa Flavours' => 'images/restaurants/ethiopian.jpg',
            'Havana Street' => 'images/restaurants/caribbean.jpg',
        ];

        return isset($imageMap[$name]) ? asset($imageMap[$name]) : null;
    }
}
